import { GameDefinition } from "@/types/game";

export const GAMES_CATALOG: GameDefinition[] = [
  {
    id: "matching",
    titleKey: "games.matching.title",
    descriptionKey: "games.matching.subtitle",
    icon: "puzzle",
    available: true,
    levels: ["easy", "medium", "hard"],
  },
  {
    id: "letters",
    titleKey: "games.letters.title",
    descriptionKey: "games.letters.subtitle",
    icon: "alphabet",
    available: true,
    levels: ["easy", "medium", "hard"],
  },
  {
    id: "numbers",
    titleKey: "games.numbers.title",
    descriptionKey: "games.numbers.subtitle",
    icon: "numbers",
    available: true,
    levels: ["easy", "medium", "hard"],
  },
  {
    id: "colors",
    titleKey: "games.colors.title",
    descriptionKey: "games.colors.subtitle",
    icon: "shapes",
    available: true,
    levels: ["easy", "medium", "hard"],
  },
  {
    id: "memory",
    titleKey: "games.memory.title",
    descriptionKey: "games.memory.subtitle",
    icon: "brain",
    available: true,
    levels: ["easy", "medium", "hard"],
  },
  {
    id: "puzzle",
    titleKey: "games.puzzle.title",
    descriptionKey: "games.puzzle.subtitle",
    icon: "pieces",
    available: true,
    levels: ["easy", "medium", "hard"],
  },
  {
    id: "coloring",
    titleKey: "games.coloring.title",
    descriptionKey: "games.coloring.subtitle",
    icon: "palette",
    available: true,
    levels: ["easy", "medium", "hard"],
  },
  {
    id: "sorting",
    titleKey: "games.sorting.title",
    descriptionKey: "games.sorting.subtitle",
    icon: "boxes",
    available: true,
    levels: ["easy", "medium", "hard"],
  },
  {
    id: "hijaiyah",
    titleKey: "games.hijaiyah.title",
    descriptionKey: "games.hijaiyah.subtitle",
    icon: "quran",
    available: true,
    levels: ["easy", "medium", "hard"],
  },
  {
    id: "detective",
    titleKey: "games.detective.title",
    descriptionKey: "games.detective.subtitle",
    icon: "search",
    available: true,
    levels: ["easy", "medium", "hard"],
  },
  {
    id: "tracing",
    titleKey: "games.tracing.title",
    descriptionKey: "games.tracing.subtitle",
    icon: "pencil",
    available: true,
    levels: ["easy", "medium", "hard"],
  },
  {
    id: "adab",
    titleKey: "games.adab.title",
    descriptionKey: "games.adab.subtitle",
    icon: "sparkles",
    available: true,
    levels: ["easy", "medium", "hard"],
  },
];

